### ISSUE TITLE
[Request] Define domain scheme and color

### ISSUE THREAD

**Issue by MrSnoozles** [MurzNN/TST-Colored-tabs#1]
Hey, 

this seems like a really useful extension to TST. Congratulations and thank you for publishing it.
I have one (probably not so small) idea how it could be improved and wanted to discuss if it's possible to achieve.

I came to your extension looking for a utility to colorize the browser or a tab based on the domain. I want to be able to define which domains gets which color, mainly for web development purposes. I'd like to be able to define something like this, to be able to distinguish faster on which version of a site I am:

- ***.local**:   green color (development version, everything you change is safe)
- **staging.\***:  orange color (staging version)
- **mydomain.com**:  red color (live version, be careful with your settings)

Is something like this possible?

**Comment by anthonyp-cs** [comment]
I'd also find this useful for web development.

Another great option would be to set the tab colour based on the prevailing colour of the favicon. It would need to be a lighter or darker shade so the favicon would still be visible, e.g. dark blue for Facebook, dark red for Gmail, etc. I've no idea if this is possible or practical!

**Comment by oxysoft** [comment]
I also downloaded Colored Tabs expecting to be able to color by domain instead of auto. Please, this would be awesome! Vivaldi is able to get a dominant color for each site as well when the page is loaded, I don't know how but it could be possible to do the same as well for this extension and have correct automatic colors for unconfigured domains.

**Comment by MurzNN** [comment]
In 0.7 version I implement feature for set custom per-host colors via direct match and via regexp too, please test it.
