### ISSUE TITLE
Broken coloring after update to version 3.8.5 of TST

### ISSUE THREAD

**Issue by Adaephon-GH** [MurzNN/TST-Colored-tabs#23]
TST Colored Tabs does not work correctly after I upgraded TST to version 3.8.5
Firefox version : 89.0.2 (64-bit) Linux
TST version : 3.8.5
TST-colored-tabs version : 0.7

TST 3.8.5 seems to have introduced a new element named `tab-item-substance` below `tab-item` in the DOM structure. While the `coloredTabs*` classes are still applied to the `tab-item` elements, the class is not inherited by the `tab-item-substance` element.

From the looks of it `tab-item` spans the whole width of tab bar, while `tab-item-substance` is then the actual tab, which might be indented due to the tree structure. This means that depending on the theme chosen in TST either the full width is colored with the tree-structure only visible due to indentation of the favicon and text (happens with Proton and Sidebar themes) or the tabs themselves all have the same default color with colorization only visible to the left of indented tabs (happens with Photon and High Contrast).

**Comment by shr1k** [comment]
The creator of TST @piroor has helpfully submitted a PR to fix this issue [here](#24) :smiley:

**Comment by MurzNN** [comment]
Thanks for reporting and sorry for delayed fix! Fixed via #24, included in new version 0.7.1, published on Mozilla Addons too.../
