### ISSUE TITLE
Colored tabs not working

### ISSUE THREAD

**Issue by NeilsC** [MurzNN/tst-colored-tabs#32]
Tab colors are not working. All tabs are the same color, and per-host rules are not working. 

System details:
Firefox 102.0.1 64-bit
Linux (popOS)
Tree Styled Tabs 3.8.26
TST Colored Tabs 0.7.1

Screenshots

![tab_view](https://user-images.githubusercontent.com/1214412/181404914-46421924-2ab8-4360-af95-34d447567209.png)

![host_prefs](https://user-images.githubusercontent.com/1214412/181404927-78dcc934-e00b-4672-a400-5dae5acd5c06.png)

**Comment by bgigous** [comment]
Your regular expression looks incorrect, try:

`.*reddit.com.*`

Then saving will color reddit.com tabs to green. Making that stick, where TST Colored Tabs will apply that color to those tabs next without the button I have yet to figure out.

**Comment by NeilsC** [comment]
You're correct, this was user error. Thank you for the help!
