### ISSUE TITLE
[Request] Color tabs by tree

### ISSUE THREAD

**Issue by schmurtzm** [MurzNN/TST-Colored-tabs#6]
## **Short description :** 
Colors the tabs trees when a child tab is opened , I mean that each tree could be colored in a different color : it's very useful to find quickly the different sections of your navigation ! 
The idea is to add an option to TST-Colored-tabs that allow to color tabs in the same color for each tree instead a color for each domain

## **Expected result :**
(a click on a link opens a new tab in the same color of the current parent tab, the main parent tab is colored only when a child tab is opened).
### Example : 
![Example](https://gitlab.com/kroppy/TreeTabs/uploads/eae7723fea0e2becec70c8ea77956327/tabexample.JPG)
<sub>(screenshot based on the behaviour of the old "[Tab Kit](https://github.com/tabkit/tabkit2)" extension)</sup>

## **Actual result :** 
All tabs have different colors, not easy to distinguish the different sections.
![image](https://user-images.githubusercontent.com/7110113/60842310-1e008500-a1d4-11e9-8452-f3f25fb23ae0.png)

## **Environment :**
Platform (OS): Windows 10
Version of Firefox: 67.04
Version (or revision) of Tree Style Tab: 3.1.2

<sup>This feature has also been requested on the official source repo of TST [here](https://github.com/piroor/treestyletab/issues/2329) (without success :slightly_smiling_face: ) </sup>

Many thanks for the great addon ! :)

**Comment by schmurtzm** [comment]
### Second idea/example :
![image](https://user-images.githubusercontent.com/7110113/60767335-f667ca80-a0b6-11e9-8cd5-a039296cabb6.png)
This second example allow to combine tree coloration and tst-colored-tabs :
![image](https://user-images.githubusercontent.com/7110113/60767392-9887b280-a0b7-11e9-8c18-f4034042e156.png)

(powerful but may be a little hard to read, I think I prefer the first example of the first post) :neutral_face:

**Comment by MurzNN** [comment]
I don't plan to implement this mode in current extension, because main logic of this extension is color, based on hostname. So this task is more for separate extension, that can be as fork of my extension. Maybe I make it later, if have enough time for this. Also you can lookup this extension https://addons.mozilla.org/ru/firefox/addon/colortabgroup/?src=search
